import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import { ReactFlowProvider } from "reactflow";
import { DatasetMetaHeader } from "../../components/datasets/DatasetMetaHeader";

const mockSetDatasetRevealId = jest.fn();
jest.mock("../../providers/DatasetPaletteContext", () => ({
  useDatasetPalette: () => ({
    datasetRevealId: null,
    setDatasetRevealId: mockSetDatasetRevealId,
    installedComputedByProducer: new Map(),
  }),
}));

const source = {
  datasetId: "computed.node-a",
  title: "Blocks Output",
  format: "parquet" as const,
  origin: "computed" as const,
};

/** useHeaderIconDragClick activates on a pointerUp with no drag. */
function clickBadge(el: HTMLElement) {
  fireEvent.pointerDown(el, { clientX: 10, clientY: 10 });
  fireEvent.pointerUp(el, { clientX: 10, clientY: 10 });
}

describe("DatasetMetaHeader", () => {
  beforeEach(() => mockSetDatasetRevealId.mockClear());

  test("consumer variant renders the DATASET pill", () => {
    render(<DatasetMetaHeader source={source} variant="consumer" />, { wrapper: ReactFlowProvider });
    expect(screen.getByRole("button")).toHaveTextContent("DATASET");
    expect(screen.getByRole("button").getAttribute("aria-label")).toContain("dataset");
  });

  test("producer variant renders the OUTPUT pill with a 'Generated by this node' tooltip", () => {
    render(<DatasetMetaHeader source={source} variant="producer" />, { wrapper: ReactFlowProvider });
    const btn = screen.getByRole("button");
    expect(btn).toHaveTextContent("OUTPUT");
    expect(btn.getAttribute("aria-label")).toContain("output");
    expect(btn.getAttribute("title")).toContain("Generated by this node");
  });

  test("clicking reveals the linked dataset in the palette", () => {
    render(<DatasetMetaHeader source={source} variant="producer" />, { wrapper: ReactFlowProvider });
    clickBadge(screen.getByRole("button"));
    expect(mockSetDatasetRevealId).toHaveBeenCalledWith("computed.node-a");
  });

  test("applies the vibrant class only when the node is selected", () => {
    const { rerender } = render(<DatasetMetaHeader source={source} />, { wrapper: ReactFlowProvider });
    expect(screen.getByRole("button").className).not.toContain("datasetBadgeSelected");
    rerender(<DatasetMetaHeader source={source} selected />);
    expect(screen.getByRole("button").className).toContain("datasetBadgeSelected");
  });

  test("does not reveal while a suggestion is active", () => {
    render(<DatasetMetaHeader source={source} suggestionActive />, { wrapper: ReactFlowProvider });
    clickBadge(screen.getByRole("button"));
    expect(mockSetDatasetRevealId).not.toHaveBeenCalled();
  });
});
