"""Generate the pinned wrapper for the reference preview runner (dev/98).

The build workspace runs workers under a SCRUBBED env (``PATH=/usr/bin:/bin``,
remapped ``HOME``) — nothing is findable by search, so the wrapper bakes
every absolute location at generation time (the ``CURIO_BUILD_ESBUILD``
pinning precedent) and every missing prerequisite refuses LOUDLY with the
fix named — a wrapper that would lie later is never written.

Usage::

    python -m utk_curio.tools.install_preview_runner [--dest PATH]

prints the ``export CURIO_BUILD_PREVIEW_RUNNER=…`` setup line (and the
reminder to drop ``CURIO_BUILD_PREVIEW_POLICY=skip``).
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path


class GenerationError(SystemExit):
    pass


def _repo_root() -> Path:
    # tools/ -> utk_curio/ -> repo root
    return Path(__file__).resolve().parents[2]


def _node_modules() -> Path:
    return _repo_root() / "utk_curio" / "frontend" / "urban-workflows" / "node_modules"


def _require_file(path: Path, *, what: str, fix: str) -> Path:
    if not path.is_file():
        raise GenerationError(
            f"cannot generate the preview runner wrapper: {what} is missing at "
            f"{path} — {fix}"
        )
    return path


def _browsers_path() -> Path:
    """Playwright's browser cache — honored env override, else the platform
    default; a cache without chromium refuses naming the install command."""
    override = (os.environ.get("PLAYWRIGHT_BROWSERS_PATH") or "").strip()
    if override:
        base = Path(override)
    elif sys.platform == "darwin":
        base = Path.home() / "Library" / "Caches" / "ms-playwright"
    else:
        base = Path.home() / ".cache" / "ms-playwright"
    if not base.is_dir() or not any(base.glob("chromium*")):
        raise GenerationError(
            "cannot generate the preview runner wrapper: no chromium in the "
            f"playwright browser cache ({base}) — run: python -m playwright "
            "install chromium"
        )
    return base


def generate(dest: Path) -> Path:
    """Resolve every baked path (loudly) and write the executable wrapper."""
    try:
        import playwright  # noqa: F401
    except ImportError as exc:
        raise GenerationError(
            "cannot generate the preview runner wrapper: the 'playwright' "
            "python package is not importable in this interpreter — install "
            "it in the environment Curio runs under"
        ) from exc

    node_modules = _node_modules()
    react_umd = _require_file(
        node_modules / "react" / "umd" / "react.production.min.js",
        what="React's UMD build",
        fix="run npm install in utk_curio/frontend/urban-workflows",
    )
    react_dom_umd = _require_file(
        node_modules / "react-dom" / "umd" / "react-dom.production.min.js",
        what="ReactDOM's UMD build",
        fix="run npm install in utk_curio/frontend/urban-workflows",
    )
    reactflow_umd = node_modules / "reactflow" / "dist" / "umd" / "index.js"
    browsers = _browsers_path()
    runner = _require_file(
        Path(__file__).resolve().parent / "preview_runner.py",
        what="the reference runner script", fix="repo checkout is incomplete",
    )

    lines = [
        "#!/bin/sh",
        "# Generated by: python -m utk_curio.tools.install_preview_runner",
        "# (dev/98 — regenerate after moving the conda env or reinstalling",
        "#  node_modules; every path below was verified at generation time.)",
        f'export PLAYWRIGHT_BROWSERS_PATH="{browsers}"',
        f'export CURIO_PREVIEW_REACT_UMD="{react_umd}"',
        f'export CURIO_PREVIEW_REACT_DOM_UMD="{react_dom_umd}"',
    ]
    if reactflow_umd.is_file():
        lines.append(f'export CURIO_PREVIEW_REACTFLOW_UMD="{reactflow_umd}"')
    lines.append(f'exec "{sys.executable}" "{runner}" "$@"')

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return dest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the pinned reference preview-runner wrapper (dev/98).")
    parser.add_argument(
        "--dest", type=Path,
        default=_repo_root() / ".curio" / "preview-runner",
        help="wrapper path (default: <repo>/.curio/preview-runner)")
    args = parser.parse_args(argv)
    dest = generate(args.dest)
    print(f"wrote {dest}")
    print("operator setup:")
    print(f'  export CURIO_BUILD_PREVIEW_RUNNER="{dest}"')
    print("  # and DROP CURIO_BUILD_PREVIEW_POLICY=skip — a configured runner")
    print("  # makes the skip declaration stale.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
