/**
 * WKB to GeoJSON geometry.
 *
 * GeoParquet stores geometry as binary WKB, so that is what the Arrow
 * artifact path carries; every consumer in the canvas expects GeoJSON, and
 * `parseOutput` built that server-side by calling `gdf.to_json()`. Doing it
 * here instead is what lets a geodataframe skip the GeoJSON construction
 * entirely: on the stress job's 100-user tier the Arrow path served a
 * geodataframe in 0.006s against 1.183s, and 2.1 MB against 9.0 MB.
 *
 * Hand-written rather than a dependency. WKB is a fixed-layout binary format
 * that has not changed since 1999 and this is ~150 lines of it, against `wkx`
 * (unmaintained) or `@loaders.gl/wkt` (pulls a loader framework). Notably NOT
 * duckdb-wasm's `ST_AsGeoJSON`: that fetches its spatial extension from
 * extensions.duckdb.org on every fresh init, has already failed a CI map node
 * (#318, see duckdbExtensionRetry.ts), and materialising GeoJSON is the cost
 * this path exists to avoid.
 *
 * Tested against a fixture generated by shapely, the encoder that writes
 * these bytes: src/tests/fixtures/wkb-geometries.json, both byte orders,
 * every geometry type, including the empty cases.
 */

const POINT = 1;
const LINESTRING = 2;
const POLYGON = 3;
const MULTIPOINT = 4;
const MULTILINESTRING = 5;
const MULTIPOLYGON = 6;
const GEOMETRYCOLLECTION = 7;

export type GeoJsonGeometry =
    | { type: string; coordinates: any }
    | { type: "GeometryCollection"; geometries: GeoJsonGeometry[] };

class Reader {
    private at = 0;
    private littleEndian = true;

    constructor(private readonly view: DataView) {}

    byteOrder(): void {
        this.littleEndian = this.view.getUint8(this.at++) === 1;
    }

    uint32(): number {
        const value = this.view.getUint32(this.at, this.littleEndian);
        this.at += 4;
        return value;
    }

    float64(): number {
        const value = this.view.getFloat64(this.at, this.littleEndian);
        this.at += 8;
        return value;
    }
}

type Header = { type: number; dimensions: number };

function readHeader(reader: Reader): Header {
    reader.byteOrder();
    const raw = reader.uint32();
    // Two spellings of dimensionality are in the wild, and they must not be
    // read at the same time. EWKB (what shapely writes) puts Z, M and SRID in
    // the high bits, leaving the type in the low byte. ISO WKB puts it in the
    // thousands digit, so PointZ is 1001 and the type is the remainder.
    //
    // Applying both rules at once is a real bug and a quiet one: EWKB PointZ
    // is 0x80000001, whose thousands digit reads as 3, which says ZM, which
    // reads a fourth ordinate that is not there and walks off the end of the
    // row. The fixture's Z cases are what caught it.
    const isEwkb = (raw & 0xe0000000) !== 0;
    const isoDimensions = isEwkb ? 0 : Math.floor((raw % 4000) / 1000);
    const hasZ = isEwkb ? (raw & 0x80000000) !== 0 : isoDimensions === 1 || isoDimensions === 3;
    const hasM = isEwkb ? (raw & 0x40000000) !== 0 : isoDimensions === 2 || isoDimensions === 3;
    if (isEwkb && (raw & 0x20000000) !== 0) {
        // EWKB can carry the SRID inline. The CRS comes from the GeoParquet
        // metadata instead, so this is read past rather than kept.
        reader.uint32();
    }
    return {
        type: isEwkb ? raw & 0xff : raw % 1000,
        dimensions: 2 + (hasZ ? 1 : 0) + (hasM ? 1 : 0),
    };
}

function readCoordinate(reader: Reader, dimensions: number): number[] {
    const coordinate = new Array(dimensions);
    for (let i = 0; i < dimensions; i++) coordinate[i] = reader.float64();
    return coordinate;
}

function readCoordinates(reader: Reader, dimensions: number): number[][] {
    const count = reader.uint32();
    const out = new Array(count);
    for (let i = 0; i < count; i++) out[i] = readCoordinate(reader, dimensions);
    return out;
}

function readGeometry(reader: Reader): GeoJsonGeometry {
    const { type, dimensions } = readHeader(reader);
    switch (type) {
        case POINT: {
            const coordinates = readCoordinate(reader, dimensions);
            // An empty point is written as NaN coordinates, and GeoJSON spells
            // that as an empty coordinate array.
            return Number.isNaN(coordinates[0])
                ? { type: "Point", coordinates: [] }
                : { type: "Point", coordinates };
        }
        case LINESTRING:
            return { type: "LineString", coordinates: readCoordinates(reader, dimensions) };
        case POLYGON: {
            const ringCount = reader.uint32();
            const rings = new Array(ringCount);
            for (let i = 0; i < ringCount; i++) rings[i] = readCoordinates(reader, dimensions);
            return { type: "Polygon", coordinates: rings };
        }
        case MULTIPOINT:
        case MULTILINESTRING:
        case MULTIPOLYGON: {
            // Each part carries its own byte order and type, so they are read
            // as whole geometries and unwrapped.
            const count = reader.uint32();
            const parts = new Array(count);
            for (let i = 0; i < count; i++) {
                parts[i] = (readGeometry(reader) as { coordinates: any }).coordinates;
            }
            const name =
                type === MULTIPOINT ? "MultiPoint"
                : type === MULTILINESTRING ? "MultiLineString"
                : "MultiPolygon";
            return { type: name, coordinates: parts };
        }
        case GEOMETRYCOLLECTION: {
            const count = reader.uint32();
            const geometries = new Array(count);
            for (let i = 0; i < count; i++) geometries[i] = readGeometry(reader);
            return { type: "GeometryCollection", geometries };
        }
        default:
            throw new Error(`unsupported WKB geometry type ${type}`);
    }
}

/** Decode one WKB value. Null in, null out: a row may have no geometry. */
export function wkbToGeoJSON(bytes: Uint8Array | ArrayBuffer | null | undefined): GeoJsonGeometry | null {
    if (bytes == null) return null;
    const array = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
    if (array.byteLength === 0) return null;
    const view = new DataView(array.buffer, array.byteOffset, array.byteLength);
    return readGeometry(new Reader(view));
}
