/**
 * A node references a dataset two ways; both must count (#205).
 *
 * Reported as: install a dataset, build a Data Loading node that uses it, click
 * the dataset in the palette — and get "No nodes on the canvas use this
 * dataset". The lookup only knew about BINDINGS (``datasetSource`` /
 * ``datasetRefs`` / ``appliedDatasets``), which are written by exactly two drag
 * gestures. A loader whose ``curio_dataset_path`` call was typed, pasted,
 * edited or generated by an agent has no binding at all — and that call is the
 * canonical, portable reference, the one the backend resolves per execution.
 */
import { datasetIdsInCode } from "../../services/datasetCatalog/datasetLoaderSnippets";
import { nodeLinkedDatasetIds, isNodeLinkedToAnyDataset } from "../../services/datasetCatalog";

describe("datasetIdsInCode", () => {
  test("finds a double-quoted call", () => {
    expect(datasetIdsInCode('df = load(curio_dataset_path("data.urbanlab.acs@1"))')).toEqual([
      "data.urbanlab.acs@1",
    ]);
  });

  test("finds a single-quoted call", () => {
    // Users edit the generated code, so both quote styles occur — matching the
    // backend's own scan.
    expect(datasetIdsInCode("curio_dataset_path('imported.x@1')")).toEqual(["imported.x@1"]);
  });

  test("tolerates whitespace inside the call", () => {
    expect(datasetIdsInCode('curio_dataset_path(  "a.b@1"  )')).toEqual(["a.b@1"]);
  });

  test("finds every distinct id, once", () => {
    const code = [
      'a = curio_dataset_path("one@1")',
      'b = curio_dataset_path("two@1")',
      'c = curio_dataset_path("one@1")',
    ].join("\n");
    expect(datasetIdsInCode(code)).toEqual(["one@1", "two@1"]);
  });

  test("rejects mismatched quotes", () => {
    // The backreference in the pattern is what makes this not a reference;
    // without it a broken call would register as a usage.
    expect(datasetIdsInCode("curio_dataset_path(\"x@1')")).toEqual([]);
  });

  test("rejects an id outside the safe charset", () => {
    // The generators only ever emit ids matching the whitelist, and an id with
    // a quote or backslash could not have come from one.
    expect(datasetIdsInCode('curio_dataset_path("../etc/passwd")')).toEqual([]);
    expect(datasetIdsInCode('curio_dataset_path("")')).toEqual([]);
  });

  test("ignores a different function of a similar name", () => {
    expect(datasetIdsInCode('my_curio_dataset_path_helper("x@1")')).toEqual([]);
  });

  test("is bounded", () => {
    // Matches the backend's MAX_EXEC_DATASET_IDS: generated or pathological
    // code must not turn a palette click into a long scan.
    const code = Array.from({ length: 50 }, (_, i) => `curio_dataset_path("d${i}@1")`).join("\n");
    expect(datasetIdsInCode(code)).toHaveLength(32);
  });

  test("survives anything that is not code", () => {
    for (const input of [undefined, null, "", 42, {}]) {
      expect(datasetIdsInCode(input)).toEqual([]);
    }
  });

  test("does not depend on call order", () => {
    // A shared module-level /g regex would carry lastIndex between calls.
    const code = 'curio_dataset_path("only@1")';
    expect(datasetIdsInCode(code)).toEqual(["only@1"]);
    expect(datasetIdsInCode(code)).toEqual(["only@1"]);
  });
});

describe("nodeLinkedDatasetIds with code references", () => {
  test("a hand-authored loader counts as using its dataset", () => {
    // The reported case, stated directly: no bindings, just the call.
    const data = { code: 'df = pd.read_csv(curio_dataset_path("data.urbanlab.acs@1"))' };
    expect(nodeLinkedDatasetIds(data)).toEqual(["data.urbanlab.acs@1"]);
    expect(isNodeLinkedToAnyDataset(data, ["data.urbanlab.acs@1"])).toBe(true);
  });

  test("a palette node's untouched defaultCode counts too", () => {
    // What a palette-created node carries before the user edits it, and what
    // the editor renders.
    const data = { defaultCode: 'curio_dataset_path("seeded@1")' };
    expect(isNodeLinkedToAnyDataset(data, ["seeded@1"])).toBe(true);
  });

  test("bindings and code are unioned, not duplicated", () => {
    const data = {
      datasetSource: { datasetId: "both@1" },
      code: 'curio_dataset_path("both@1")',
    };
    expect(nodeLinkedDatasetIds(data)).toEqual(["both@1"]);
  });

  test("a call for a different dataset does not match", () => {
    const data = { code: 'curio_dataset_path("other@1")' };
    expect(isNodeLinkedToAnyDataset(data, ["wanted@1"])).toBe(false);
  });
});
