"""Extension snapshots + the merge planner (memo dev/89 §3.2).

Extending an installed package never builds in the installed directory:
:func:`snapshot_installed_package` copies an ELIGIBLE package (user-editable —
never ``readOnly``, never the seeded builtin) into an in-memory, digest-pinned
:class:`ExtensionSnapshot`, and :func:`plan_extension` computes the
file- and template-level plan against a validated build request.

Invariants (dev/89 §3.2, v1):

* **No implicit removal** — merged output = base files ∪ draft overrides, so
  a file can never vanish; a draft manifest missing a base template id is
  refused as implicit template removal.
* **Generalized preservation** — EVERY untouched base file (sources, starters,
  scripts, assets, README, LICENSE, unknown-but-allowed files) is carried
  forward byte-identical, generalizing the factory's
  ``preserve_unedited_sources`` beyond starter files.
* **One normalized diff** — :meth:`MergePlan.to_payload` is the single diff
  shape the review UI renders AND the apply path re-verifies
  (:func:`verify_base_unchanged`), so displayed and executed changes cannot
  diverge.
* **Stale bases refuse loudly** — a request whose pinned ``baseDigest`` no
  longer matches the snapshot is an :class:`ExtensionError`, never a silent
  overwrite of a newer package.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any, Mapping

from utk_curio.backend.app.packages.build_models import PackageBuildRequest
from utk_curio.backend.app.packages.installer import (
    _MAX_FILE_BYTES,
    _MAX_TOTAL_BYTES,
)
from utk_curio.backend.app.packages.manifest import (
    ManifestError,
    PackageManifest,
    load_packageage_manifest,
)
from utk_curio.backend.app.packages.storage import package_dir

# Builder-owned files never participate in the file-level plan: the manifest
# arrives as the request's typed field and integrity is regenerated by the
# packager over the final archive.
_PLAN_EXCLUDED_FILES = frozenset({"manifest.json", "integrity.json"})


class ExtensionError(ValueError):
    """Raised on ineligible targets, stale bases, and refused merge plans."""


@dataclass(frozen=True)
class ExtensionSnapshot:
    """A read-only, digest-pinned copy of one installed package.

    ``files`` holds every shipped file's bytes (``integrity.json`` excluded —
    it is derived state). The snapshot is taken once per build; the build
    never reads the live installed directory again (dev/89 §3.2).
    """

    dir_name: str
    manifest: PackageManifest
    files: dict[str, bytes]
    base_digest: str


def compute_files_digest(files: Mapping[str, bytes]) -> str:
    """The canonical digest over a package's file set: SHA-256 of the sorted
    ``{path: sha256(bytes)}`` map. This is the ``baseDigest`` an extend
    request pins and the value :func:`verify_base_unchanged` recomputes."""
    per_file = {path: hashlib.sha256(body).hexdigest() for path, body in files.items()}
    canonical = json.dumps(per_file, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _read_package_files(root) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    total = 0
    for entry in sorted(root.rglob("*")):
        if not entry.is_file() or entry.name == "integrity.json":
            continue
        data = entry.read_bytes()
        if len(data) > _MAX_FILE_BYTES:
            raise ExtensionError(
                f"installed file {entry.name!r} exceeds the per-file limit — "
                "refusing to snapshot"
            )
        total += len(data)
        if total > _MAX_TOTAL_BYTES:
            raise ExtensionError("installed package exceeds the total size limit")
        files[entry.relative_to(root).as_posix()] = data
    return files


def installed_package_digest(user_key: str, dir_name: str) -> str | None:
    """The current on-disk digest of one installed package, or None when the
    package is not installed. Used at Apply time for stale verification."""
    root = package_dir(user_key, dir_name)
    if not root.is_dir():
        return None
    return compute_files_digest(_read_package_files(root))


def verify_base_unchanged(user_key: str, dir_name: str, expected_base_digest: str) -> bool:
    """True when the installed package still hashes to *expected_base_digest*.

    A False here is the 409-stale path (dev/89 §4): the proposal was built
    against a base that changed — regenerate, never overwrite silently.
    """
    return installed_package_digest(user_key, dir_name) == expected_base_digest


def snapshot_installed_package(user_key: str, dir_name: str) -> ExtensionSnapshot:
    """Snapshot one ELIGIBLE installed package for extension.

    Refuses (loudly, with the reason): a package that is not installed, a
    ``readOnly`` manifest, and the seeded builtin — those targets get a new
    package with explicit lineage instead of an in-place extension.
    """
    from utk_curio.backend.app.packages.seed import BUILTIN_PACKAGE_ID

    root = package_dir(user_key, dir_name)
    if not root.is_dir():
        raise ExtensionError(f"package {dir_name} is not installed for this user")
    try:
        manifest = load_packageage_manifest(root)
    except ManifestError as exc:
        raise ExtensionError(f"package {dir_name} has an invalid manifest: {exc}") from exc
    if manifest.read_only:
        raise ExtensionError(
            f"package {dir_name} is read-only — extend by creating a new "
            "package with explicit lineage instead"
        )
    if manifest.package_id == BUILTIN_PACKAGE_ID:
        raise ExtensionError(
            f"package {dir_name} is the seeded builtin and is never extended "
            "in place"
        )
    files = _read_package_files(root)
    return ExtensionSnapshot(
        dir_name=dir_name,
        manifest=manifest,
        files=files,
        base_digest=compute_files_digest(files),
    )


@dataclass(frozen=True)
class MergePlan:
    """The normalized file- and template-level plan for one build.

    One shape serves both consumers (dev/89 §3.2): the review UI renders
    :meth:`to_payload`, and the apply path re-derives the same payload to
    prove the displayed and executed changes are identical
    (:meth:`plan_digest`).
    """

    mode: str  # "create" | "extend"
    target: str
    base_digest: str | None
    files_preserved: tuple[str, ...]
    files_modified: tuple[str, ...]
    files_added: tuple[str, ...]
    templates_preserved: tuple[str, ...]
    templates_modified: tuple[str, ...]
    templates_added: tuple[str, ...]
    warnings: tuple[str, ...] = ()

    def to_payload(self) -> dict[str, Any]:
        return {
            "mode": self.mode,
            "target": self.target,
            "baseDigest": self.base_digest,
            "files": {
                "preserved": list(self.files_preserved),
                "modified": list(self.files_modified),
                "added": list(self.files_added),
            },
            "templates": {
                "preserved": list(self.templates_preserved),
                "modified": list(self.templates_modified),
                "added": list(self.templates_added),
            },
            "warnings": list(self.warnings),
        }

    def plan_digest(self) -> str:
        canonical = json.dumps(self.to_payload(), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _raw_templates_by_id(manifest_raw: Mapping[str, Any], where: str) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for template in manifest_raw.get("templates") or []:
        if not isinstance(template, dict) or not isinstance(template.get("id"), str):
            raise ExtensionError(f"{where} manifest has a template without a string id")
        template_id = template["id"]
        if template_id in out:
            raise ExtensionError(f"{where} manifest declares template {template_id!r} twice")
        out[template_id] = template
    return out


def _check_behavior_key_collisions(draft_templates: Mapping[str, dict],
                                   manifest_raw: Mapping[str, Any]) -> None:
    """V1 collision rule (dev/89 §3.2): when the package registers its own
    behavior hooks (``behaviorScript`` declared), two different templates may
    not claim the same behavior key — the registration would be ambiguous."""
    if not manifest_raw.get("behaviorScript"):
        return
    by_key: dict[str, str] = {}
    for template_id, template in draft_templates.items():
        key = template.get("behavior")
        if not isinstance(key, str) or not key.strip():
            continue
        prior = by_key.get(key)
        if prior is not None:
            raise ExtensionError(
                f"behavior key {key!r} is claimed by both templates "
                f"{prior!r} and {template_id!r} — behavior keys must be unique "
                "within a package that ships a behaviorScript"
            )
        by_key[key] = template_id


def plan_create(request: PackageBuildRequest) -> MergePlan:
    """The (trivial) plan for a new package: everything is an addition."""
    if request.mode != "create":
        raise ExtensionError(f"plan_create requires a create request, got {request.mode!r}")
    draft_templates = _raw_templates_by_id(request.manifest, "draft")
    _check_behavior_key_collisions(draft_templates, request.manifest)
    return MergePlan(
        mode="create",
        target=request.target,
        base_digest=None,
        files_preserved=(),
        files_modified=(),
        files_added=tuple(sorted(request.files)),
        templates_preserved=(),
        templates_modified=(),
        templates_added=tuple(sorted(draft_templates)),
    )


def plan_extension(snapshot: ExtensionSnapshot, request: PackageBuildRequest) -> MergePlan:
    """Compute the extension plan for *request* against *snapshot*.

    Refuses: mode/target mismatches, a stale ``baseDigest``, a coordinate
    change, duplicate draft template ids, implicit template removal, and
    behavior-key collisions. Every base file the draft does not override is
    preserved byte-identical (see :func:`merged_files`).
    """
    if request.mode != "extend":
        raise ExtensionError(f"plan_extension requires an extend request, got {request.mode!r}")
    if request.target != snapshot.dir_name:
        raise ExtensionError(
            f"request targets {request.target!r} but the snapshot is of "
            f"{snapshot.dir_name!r}"
        )
    if request.base_digest != snapshot.base_digest:
        raise ExtensionError(
            f"stale base: request pins digest {request.base_digest} but the "
            f"installed package hashes to {snapshot.base_digest} — regenerate "
            "the draft against the current package"
        )

    base_raw = json.loads(snapshot.files["manifest.json"].decode("utf-8"))
    base_templates = _raw_templates_by_id(base_raw, "installed")
    draft_templates = _raw_templates_by_id(request.manifest, "draft")

    missing = sorted(set(base_templates) - set(draft_templates))
    if missing:
        raise ExtensionError(
            f"draft manifest drops installed template(s) {missing} — implicit "
            "removal is refused; extensions carry every base template forward"
        )
    _check_behavior_key_collisions(draft_templates, request.manifest)

    # Requested nodes may target any MERGED template (base templates ride the
    # draft manifest — checked above), never a template that will not exist.
    for node in request.nodes:
        if node.template_id not in draft_templates:
            raise ExtensionError(
                f"requested node targets template {node.template_id!r}, which "
                "the merged package does not declare"
            )

    templates_preserved: list[str] = []
    templates_modified: list[str] = []
    templates_added: list[str] = []
    for template_id in sorted(draft_templates):
        base = base_templates.get(template_id)
        if base is None:
            templates_added.append(template_id)
        elif base == draft_templates[template_id]:
            templates_preserved.append(template_id)
        else:
            templates_modified.append(template_id)

    files_preserved: list[str] = []
    files_modified: list[str] = []
    files_added: list[str] = []
    warnings: list[str] = []
    base_files = {p: b for p, b in snapshot.files.items() if p not in _PLAN_EXCLUDED_FILES}
    for path in sorted(set(base_files) | set(request.files)):
        draft_body = request.files.get(path)
        base_body = base_files.get(path)
        if draft_body is None:
            files_preserved.append(path)  # generalized preservation — untouched
        elif base_body is None:
            files_added.append(path)
        elif draft_body == base_body:
            files_preserved.append(path)
            warnings.append(f"draft resubmitted {path} byte-identical to the base")
        else:
            files_modified.append(path)

    return MergePlan(
        mode="extend",
        target=request.target,
        base_digest=snapshot.base_digest,
        files_preserved=tuple(files_preserved),
        files_modified=tuple(files_modified),
        files_added=tuple(files_added),
        templates_preserved=tuple(templates_preserved),
        templates_modified=tuple(templates_modified),
        templates_added=tuple(templates_added),
        warnings=tuple(warnings),
    )


def merged_files(snapshot: ExtensionSnapshot, request: PackageBuildRequest) -> dict[str, bytes]:
    """The extension's output file set: every base file carried forward,
    overridden by the draft's files. ``manifest.json`` is excluded — the
    packager regenerates it from the request's typed manifest — and
    ``integrity.json`` never entered the snapshot."""
    out = {p: b for p, b in snapshot.files.items() if p not in _PLAN_EXCLUDED_FILES}
    out.update(request.files)
    return out
