"""The single source for contracts both the model and the code must agree on.

A contract is something the code enforces: change it and the model, or the
other half of the code, is wrong about what the system accepts. Each one is
defined here exactly once. Python imports it from this module; every other
consumer receives a GENERATED copy, rendered by the functions below and
written by ``scripts/generate_contracts.py``.

``GENERATED_OUTPUTS`` is the one registry of committed outputs. The CLI writes
each entry and ``test_generated_contracts`` re-renders each entry and fails on
any difference, so a hand edit to an output, or a change here that was never
regenerated, turns the suite red.

Pure and importable from an installed wheel: no I/O at import time, nothing
beyond the standard library.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

#: Where this module lives, relative to the repository root. Named in every
#: generated header so a reader of an output knows what to edit instead.
SOURCE_MODULE = "utk_curio/backend/app/agents/contracts.py"
#: The CLI that writes the outputs, named in the same header.
GENERATOR = "scripts/generate_contracts.py"


# --- Render outcome vocabulary ---------------------------------------------
#
# A renderer Curio owns (frontend ``renderOutcome``) counts what it drew and,
# when it drew nothing, reports a journal record whose ``kind`` is
# ``empty-render:<cause>``. The cause decides who is at fault, and therefore
# whether the harness asks for a corrected document or waits on the upstream.

#: The kind a renderer stamps on an empty render, with its cause appended.
EMPTY_RENDER_KIND = "empty-render"


@dataclass(frozen=True)
class RenderCause:
    """One reason a render drew nothing."""

    name: str
    #: Whether rewriting THIS node's document is the repair. False only when
    #: nothing arrived from upstream, so no document could have drawn a thing.
    document_at_fault: bool
    description: str


CAUSE_NO_LAYERS = "no-layers"
CAUSE_NO_INPUT_ROWS = "no-input-rows"
CAUSE_NOTHING_DRAWN = "nothing-drawn"
CAUSE_EMPTY_SOURCE = "empty-source"

#: Every cause a renderer can report. The order is the vocabulary's own and new
#: causes are appended; which cause wins when several apply is decided by the
#: rule order in ``renderOutcome``.
RENDER_CAUSES: tuple[RenderCause, ...] = (
    RenderCause(
        CAUSE_NO_LAYERS, True,
        "Every layer the document asks for names data the dataflow does not produce.",
    ),
    RenderCause(
        CAUSE_NO_INPUT_ROWS, False,
        "Zero rows arrived from upstream, so the upstream node is what must change.",
    ),
    RenderCause(
        CAUSE_NOTHING_DRAWN, True,
        "Rows arrived and the document drew none of them.",
    ),
    RenderCause(
        CAUSE_EMPTY_SOURCE, True,
        "The node's own data sources loaded zero rows.",
    ),
)

#: The cause names alone, in table order.
EMPTY_RENDER_CAUSES: tuple[str, ...] = tuple(cause.name for cause in RENDER_CAUSES)

_AT_FAULT = {cause.name: cause.document_at_fault for cause in RENDER_CAUSES}


def is_document_at_fault(cause: object) -> bool:
    """Whether an empty render with this cause is the DOCUMENT's problem.

    Read from ``RENDER_CAUSES``. A cause this build does not know is treated as
    the document's fault, so a correction is still asked for: only a cause the
    table marks as not at fault spares the document.
    """
    return _AT_FAULT.get(str(cause or ""), True)


# --- Renderers -------------------------------------------------------------


def _ts_header() -> str:
    return (
        f"// Generated by {GENERATOR} from\n"
        f"// {SOURCE_MODULE}. Do not edit by hand: change the\n"
        f"// source module and run `python {GENERATOR}`.\n"
    )


def _ts_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_render_causes_ts() -> str:
    """``src/generated/renderCauses.ts``: the render outcome vocabulary."""
    causes = "".join(
        f"  /** {cause.description} */\n  {_ts_string(cause.name)},\n"
        for cause in RENDER_CAUSES
    )
    at_fault = "".join(
        f"  {_ts_string(cause.name)}: {'true' if cause.document_at_fault else 'false'},\n"
        for cause in RENDER_CAUSES
    )
    return (
        _ts_header()
        + "\n"
        + "/** The kind prefix of an empty render: `empty-render:<cause>`. */\n"
        + f"export const EMPTY_RENDER_KIND = {_ts_string(EMPTY_RENDER_KIND)};\n"
        + "\n"
        + "/** Every reason a render can draw nothing. */\n"
        + "export const RENDER_CAUSES = [\n"
        + causes
        + "] as const;\n"
        + "\n"
        + "export type RenderCause = (typeof RENDER_CAUSES)[number];\n"
        + "\n"
        + "/** Whether rewriting the node's document is the repair for each cause. */\n"
        + "export const DOCUMENT_AT_FAULT: Readonly<Record<RenderCause, boolean>> = {\n"
        + at_fault
        + "};\n"
    )


#: Every committed output: repo-relative path -> the function that renders it.
GENERATED_OUTPUTS: dict[str, Callable[[], str]] = {
    "utk_curio/frontend/urban-workflows/src/generated/renderCauses.ts": render_render_causes_ts,
}


def stale_outputs(repo_root: Path) -> list[str]:
    """The registered outputs whose file on disk differs from a fresh render."""
    stale = []
    for relative, render in GENERATED_OUTPUTS.items():
        path = Path(repo_root) / relative
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != render():
            stale.append(relative)
    return stale
