/**
 * The WKB decoder against bytes shapely actually produced.
 *
 * The fixture is generated by scripts/generate_wkb_fixture.py and pinned by a
 * Python test that regenerates and compares, so these cases cannot drift from
 * what the encoder emits. Both byte orders are covered: a decoder that
 * ignores WKB's endianness flag reads little-endian data correctly by luck.
 */
import fixture from "../fixtures/wkb-geometries.json";

import { wkbToGeoJSON } from "../../utils/wkb";

function decodeHex(hex: string): Uint8Array {
    const bytes = new Uint8Array(hex.length / 2);
    for (let i = 0; i < bytes.length; i++) {
        bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    }
    return bytes;
}

const cases = fixture as Record<string, { wkb_hex: string; geojson: any }>;

describe("wkbToGeoJSON", () => {
    it.each(Object.keys(cases))("decodes %s to the geometry shapely means", (name) => {
        const { wkb_hex, geojson } = cases[name];

        const decoded = wkbToGeoJSON(decodeHex(wkb_hex));

        expect(decoded).toEqual(geojson);
    });

    it("decodes a Z geometry keeping the third ordinate", () => {
        const decoded: any = wkbToGeoJSON(decodeHex(cases.point_z.wkb_hex));

        expect(decoded.coordinates).toHaveLength(3);
        expect(decoded.coordinates[2]).toBe(3);
    });

    it("returns null for a row with no geometry", () => {
        // GeoParquet leaves the cell null; a feature with no geometry is
        // valid GeoJSON and the canvas already handles it.
        expect(wkbToGeoJSON(null)).toBeNull();
        expect(wkbToGeoJSON(undefined)).toBeNull();
        expect(wkbToGeoJSON(new Uint8Array([]))).toBeNull();
    });

    it("refuses a type it does not know rather than inventing a shape", () => {
        // Byte order 1, type 99: not a WKB geometry any writer produces.
        expect(() => wkbToGeoJSON(decodeHex("0163000000"))).toThrow(/unsupported WKB/);
    });

    it("reads a Uint8Array that is a view into a larger buffer", () => {
        // Arrow hands out views over one big allocation, so a decoder that
        // ignores byteOffset reads another row's bytes.
        const original = decodeHex(cases.point.wkb_hex);
        const padded = new Uint8Array(original.length + 8);
        padded.set(original, 4);
        const view = padded.subarray(4, 4 + original.length);

        expect(wkbToGeoJSON(view)).toEqual(cases.point.geojson);
    });
});
